Dev update fit mult imputed obs outcome
codeblue-team/basecamb pull request #26
Opened 2021-06-03 20:27 UTC by Besttd

After finding out that Hmisc's `fit.mult.impute()` has a subset option, I've updated basecamb's `fit_mult_impute_obs_outcome()` to use the subset argument instead of implementing it ourselves.
Effectively, `fit_mult_impute_obs_outcome()` is now a wrapper for Hmisc's `fit.mult.impute()`.

I also changed the helper function we wrote to "deprecated" in its description but left it for the moment. Please let me know if you think we can remove it. It would not be very hard to reimplement it.

All tests passed.

2021-06-04 19:01 UTC, p-mq requested changes
Please use proper deprecation (https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Deprecated) for the helper function. Rest looks great!

2021-06-04 19:01 UTC, p-mq commented on R/Fit_mult_impute_observed_outcome.R
> +#' !!! Deprecated !!! This used to be a helper function for basecamb::fit_mult_impute_obs_outcome
Was there a reason why we made this a public function in the first place rather than keeping it internal? Is there much use that cannot be replicated with `apply_function_to_imputed_data()`?

Removing or hiding the function without a transition period is not great style. To properly deprecate the function, leave the namespace and functionality unaffected and use the `.Deprecated` function (https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Deprecated).
```suggestion
#' .Deprecated(new='apply_function_to_imputed_data', package='basecamb')
```

That call should be the first call in the function body. Feel free to hint at deprecation in the description, but a simple notice should do. the `.Deprecated` call automatically issues a message whenever the function is used.

2021-06-04 19:01 UTC, p-mq commented on NAMESPACE
> -export(remove_missing_from_mids)
See deprecation notice below

2021-06-04 19:01 UTC, p-mq commented on R/Fit_mult_impute_observed_outcome.R
> -#' @export
See deprecation notice above

2021-06-06 11:17 UTC, Besttd commented on R/Fit_mult_impute_observed_outcome.R
> +#' !!! Deprecated !!! This used to be a helper function for basecamb::fit_mult_impute_obs_outcome
agreed

2021-06-06 11:20 UTC, Besttd commented on NAMESPACE
> -export(remove_missing_from_mids)
agreed

2021-06-06 11:20 UTC, p-mq approved these changes

2021-06-06 11:21 UTC, merged